<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <base href="http://localhost/Site/" />
    
    <link rel="shortcut icon" href="assets/ico/favicon.ico">

    <title><?php echo $title; ?></title>

		<link rel="stylesheet" href="assets/css/bootstrap.min.css">
		<link rel="stylesheet" href="assets/css/uploadify.css">
		<link rel="stylesheet" href="assets/css/font-awesome.min.css">
		<link rel="stylesheet" href="assets/css/dashboard.css">
		<link rel="stylesheet" href="assets/css/bootstrap-colorpicker.min.css">
		
		
		<script src="assets/js/jquery-1.11.0.min.js"></script>
		<script src="assets/js/jquery.uploadify.min.js" type="text/javascript"></script>
		<script src="assets/js/jquery.form.min.js" type="text/javascript"></script>
		<script src="assets/js/ajaxfileupload.js" type="text/javascript"></script>
		<script src="assets/js/bootstrap-colorpicker.min.js" type="text/javascript"></script>
		<script src="assets/js/base.js" type="text/javascript"></script>
		<script src="assets/js/bootstrap.min.js"></script>
		
		
		<!-- Terceiros -->
		<script src="assets/3rd/ckeditor/ckeditor.js" type="text/javascript"></script>
		<script src="assets/3rd/ckeditor/adapters/jquery.js" type="text/javascript"></script>
		
		
    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
    	.alinhamento{
    		vertical-align: middle;
    		font-size: 18px;
    	}
    	
    	.centro {
			width: 200px;
			margin: 0 auto;
			margin-top: 20%;
			text-align: center;
		}
    </style>
    
    <script type="text/javascript">
	
			
			function Postar(e, retorno){
				$(e).submit(function() { return false; } );
				$(retorno).html('<i>Carregando...</i>');
				var data = $(e).serialize();
				var origem = $(e).attr('action');
				
				//console.log(data);
				$.post(origem,data,function(res){
					$(retorno).html(res);
				});
				
				
				
				return false;
			}
			
			function Abrir(e, retorno){
				var origem = $(e).attr('href');
				$(retorno).html('<i>Carregando...</i>');
				$(retorno).load(origem);
				return false;
			}
			
			function Confirma(e, retorno, msg){
				var a;
				a = window.confirm(msg);
				if(a){
					Abrir(e, retorno);
				}
				return false;
			}
		</script>
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <!-- <span class="icon-bar"><a href="admin/playlists"><i class="fa fa-music alinhamento"></i> Playlists</a></span>
            <span class="icon-bar"><a href="admin/playlists"><i class="fa fa-music alinhamento"></i> Playlists</a></span> -->
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><?php echo $title; ?></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <!-- <li><a href="#">Dashboard</a></li>
            <li><a href="#">Opções</a></li>
            <li><a href="#">Perfil</a></li>
            <li><a href="#">Ajuda</a></li> -->
          </ul>
          <!--form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Procurar...">
          </form-->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li <?php if($view_lugar=='home'){ ?> class="active" <?php } ?>><a href="admin/"><i class="fa fa-home fa-2x alinhamento"></i> Início</a></li>
            <li <?php if($view_lugar=='postagens'){ ?> class="active" <?php } ?>><a href="admin/postagens"><i class="fa fa-file-text-o alinhamento"></i> Postagens</a></li>
            <li <?php if($view_lugar=='galerias'){ ?> class="active" <?php } ?>><a href="admin/galerias"><i class="fa fa-photo alinhamento"></i> Galerias</a></li>
            <li <?php if($view_lugar=='textos'){ ?> class="active" <?php } ?>><a href="admin/textos"><i class="fa fa-thumb-tack alinhamento"></i> Textos Fixos</a></li>
            <!-- <li <?php if($view_lugar=='usuarios'){ ?> class="active" <?php } ?>><a href="admin/usuarios"><i class="fa fa-users alinhamento"></i> Usuários</a></li> -->
            <li <?php if($view_lugar=='preferencias'){ ?> class="active" <?php } ?>><a href="admin/preferencias"><i class="fa fa-paint-brush alinhamento"></i> Preferências</a></li>
            <li <?php if($view_lugar=='email'){ ?> class="active" <?php } ?>><a href="http://localhost/webmail" target="_blank"><i class="fa fa-at alinhamento"></i> E-mail</a></li>
          </ul>

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main" id="conteudo">
			