<h1>Galerias</h1>

<div id="retornoGalerias"></div><br />
<div id="galeriasForm">

</div>


<a href="admin/galeriasForm" id="abreGaleriasForm"></a>

	<script type="text/javascript">
		Abrir('#abreGaleriasForm','#galeriasForm');
	</script>



<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Listar Galerias</h3>
  </div>
  <div class="panel-body" id="galerias" style="min-height:250px;">
  </div>
</div>

	<a href="admin/galeriasListar" id="abreGaleriasListar"></a>

	<script type="text/javascript">
	Abrir('#abreGaleriasListar','#galerias');
	</script>