<h1>Postagens</h1>

<div id="retornoPostagem"></div><br />
<div id="postagemForm">

</div>


<a href="admin/postagensForm" id="abrePostagensForm"></a>

	<script type="text/javascript">
		Abrir('#abrePostagensForm','#postagemForm');
	</script>



<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Listar Postagens</h3>
  </div>
  <div class="panel-body" id="postagens" style="min-height:250px;">
  </div>
</div>

	<a href="admin/postagensListar" id="abrePostagensListar"></a>

	<script type="text/javascript">
	Abrir('#abrePostagensListar','#postagens');
	</script>