<table class="table table-bordered table-condensed table-responsive table-striped">
	<thead>
		<tr>
			<th>Título</th>
			<th>Data</th>
			<th colspan="2">Ações</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($view_postagens as $postagem){ ?>
		<tr>
			<td><?php echo $postagem[titulo]; ?></td>
			<td><?php echo date("d/m/Y",strtotime($postagem[data])); ?></td>
			<td>
				<a href="admin/postagensForm/editar/<?php echo $postagem[id]; ?>" class="btn btn-warning" onclick="return Abrir(this,'#postagemForm');">
					<i class="fa fa-pencil fa-lg"></i>
				</a>

				<a href="admin/postagensExcluir/id/<?php echo $postagem[id]; ?>/" onclick="return Confirma(this, '#retornoPostagem','Deseja realmente excluir esta postagem?');" class="btn btn-danger">
					<i class="fa fa-trash-o fa-lg"></i>
				</a>
			</td>
		</tr>
		<?php } ?>
	</tbody>
</table>

<div class="clearfix"><br /></div>

	<div class="col-lg-6">
		<a <?php if($view_pagina>0){ ?>href="admin/postagensListar/pagina/<?php echo $view_pagina-1; ?>" onclick="return Abrir(this,'#postagens');" <?php } else echo 'href="javascript:;"'; ?> class="btn btn-primary"><i class="fa fa-arrow-left fa-2x"></i></a>
		
		<a <?php if($view_total==$view_limite){ ?>href="admin/postagensListar/pagina/<?php echo $view_pagina+1; ?>" onclick="return Abrir(this,'#postagens');" <?php } else echo 'href="javascript:;"'; ?> class="btn btn-primary"><i class="fa fa-arrow-right fa-2x"></i></a>
	</div>