<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title"><?php if($view_postagem[0]['id']) echo 'Editar'; else echo 'Nova'; ?> Postagem</h3>
  </div>
  
  <div class="panel-body">
	<form action="admin/postagensSalvar" id="formPostagem" method="POST" onsubmit="return Postar(this,'#retornoPostagem');">
	    
		<div class="col-lg-12">
			Título:<br />
			<input type="text" class="form-control" name="titulo" value="<?php echo $view_postagem[0]['titulo']; ?>" />
		</div>
		<div class="clearfix"><br /></div>
		
		<div class="col-lg-12">
		    Texto:<br />
		    <textarea name="texto" class="postagem" style="width: 100%; height: 200px;"><?php echo $view_postagem[0]['texto']; ?></textarea>
		</div>
		<div class="clearfix"><br /></div>
		
		<br />
		<input type="hidden" name="modificar" value="<?php echo $view_postagem[0]['id']; ?>" />
		<input type="hidden" name="enviar" value="1" />
		<input type="submit" class="btn btn-primary" value="<?php if($view_postagem[0]['id']) echo 'Editar'; else echo 'Postar'; ?>" />
	</form>

	<script>
		$('.postagem').ckeditor({"extraPlugins": "imagebrowser","imageBrowser_listUrl" : "http://localhost/Site/uploads/media/"});
	</script>

  </div>
</div>