<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">

		<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame
		Remove this if you use the .htaccess -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<!--base href="http://<?php echo $_SERVER['HTTP_HOST'] ?>/"-->
		<title><?php echo $title; ?></title>
		<meta name="description" content="">
		<meta name="author" content="Madureira">
		
		<base href="http://localhost/Site/" />

		<meta name="viewport" content="width=device-width; initial-scale=1.0">

		<link rel="stylesheet" href="assets/css/bootstrap.min.css">
		
		<script src="assets/js/jquery-1.11.0.min.js"></script>
		
		<link rel="stylesheet" href="assets/css/navbar.css">
		<link href="assets/css/jquery.bxslider.css" rel="stylesheet" type="text/css" />

		<script type="text/javascript" src="assets/js/jquery.fancybox-1.3.4.js"></script>
		<script type="text/javascript" src="assets/js/jquery.mousewheel-3.0.4.pack.js"></script>
		<script type="text/javascript" src="assets/js/jquery.fancybox-1.3.4.pack.js"></script>
		<link rel="stylesheet" type="text/css" href="assets/css/jquery.fancybox-1.3.4.css" media="screen" />
		<link rel="stylesheet" href="assets/css/base.css">
		<link rel="stylesheet" type="text/css" media="screen" href="index/css">
		
		
		<script src="assets/js/jquery.bxslider.min.js"></script>
		
		<script src="assets/js/bootstrap.min.js"></script>
		<!-- Replace favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
		<link rel="shortcut icon" href="/favicon.ico">
		<link rel="apple-touch-icon" href="/apple-touch-icon.png">
		
		<style type="text/css">
			<?php echo $view_css; ?>
		</style>
	</head>
	

	<body>
		
	<!--Início div conteudo-->
		
		<header style="text-align: center;">
			<img src="uploads/<?php echo $view_logo; ?>" />
		</header>
		<br />

		<nav class="navbar" role="navigation" style="width: 100%; padding-left: 10%;">
		  <div class="container-fluid">
		    
		    <ul class="nav navbar-nav">
		    	<li><a href="" class="navbar-link">Home</a></li>
		    	<li><a href="pagina/sobre" class="navbar-link">Sobre</a></li>
		    	<li><a href="pagina/contato" class="navbar-link">Contato</a></li>
		    </ul>
		
		  </div><!-- /.container-fluid -->
		</nav>

	  	<div id="conteudo" style="margin: 0 auto; width: 80%; min-height: 600px; padding: 50px;">
		
		<?php if(count($view_destaque)>0){ ?>
		<div id="carousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
  	<?php for($i = 0;$i < count($view_destaque);$i++){ ?>
    <li data-target="#carousel" data-slide-to="0" <?php if(!$i){ ?>class="active"<?php } ?>></li>
    <?php } ?>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
  	
  	<?php $a=0; foreach($view_destaque as $imagem){ ?>
    <div class="item <?php if(!$a){ ?>active<?php } ?>">
      <img src="uploads/destaque_<?php echo $imagem['imagem']; ?>" width="890" height="300" />
      <div class="carousel-caption">
        
      </div>
    </div>
    <?php $a++; } ?>
    
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>
<?php } ?>
		