<form action="pagina/contato" method="post">
	<input type="text" name="nome" class="form-control" placeholder="Nome" required /><br />
	<input type="text" name="email" class="form-control" placeholder="E-mail"required /><br />
	<input type="text" name="assunto" class="form-control" placeholder="Assunto" required /><br />
	<textarea name="mensagem" class="form-control"></textarea><br />
	<input type="hidden" name="enviar" value="1" />
	<input type="submit" value="Enviar" class="btn btn-primary" />
</form>