<div>
<?php //foreach ($view_galeria as $imagem) {	?>
	<!-- <div class="box">
		<a class="fancy" href="uploads/img_<?php echo $imagem['imagem']; ?>" title="<?php echo $imagem['legenda']; ?>">
			<img src="uploads/tb_<?php echo $imagem['imagem']; ?>" />
		</a>
	</div> -->
<?php //} ?>

<script type="text/javascript">
	$(".fancy").fancybox({
		'titlePosition'	: 'inside',
		'padding' 		: '0'
	});
</script>

<br class="quebra" />
</div>
	
